---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-postgres
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-postgres
  template:
    metadata:
      labels:
        name: pttg-postgres
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
      - name: registrykey

      initContainers:

        - name: start-rds-instance
          image: quay.io/ukhomeofficedigital/docker-pttg-rds-tools:EE-12559-remove-entrypoint-2
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          command: ["/bin/bash", "-ce", "./scripts/start-rds.sh"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: management_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: management_secret_key
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
            - name: RDS_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: db_name
            - name: STOP_RDS_EVERY_NIGHT
              valueFrom:
                configMapKeyRef:
                  name: rds-config
                  key: stop_rds_every_night

        - name: pttg-postgres-bootstrap
          image: quay.io/ukhomeofficedigital/pttg-postgres:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          env:
            - name: MODE
              value: bootstrap
            - name: PTTG_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: endpoint
            - name: PTTG_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: port
            - name: PTTG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: db_name
            - name: IP_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: schema_name
            - name: IP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: application_username
            - name: IP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: application_password
            - name: ROOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: password
            - name: IP_DB_QUERY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: query_username
            - name: IP_DB_QUERY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: query_password
            - name: HMRC_AC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_database
            - name: HMRC_AC_DB_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_schema_name
            - name: HMRC_AC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_username
            - name: HMRC_AC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_password

      containers:
        - name: pttg-postgres-query
          image: quay.io/ukhomeofficedigital/pttg-postgres:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
               - SETUID
               - SETGID
          env:
            - name: MODE
              value: "query"
            - name: PTTG_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: endpoint
            - name: PTTG_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: port
            - name: PTTG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: db_name
            - name: IP_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: schema_name
            - name: IP_DB_QUERY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: query_username
            - name: IP_DB_QUERY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: query_password
            - name: HMRC_AC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_database
            - name: HMRC_AC_DB_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_schema_name
            - name: HMRC_AC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_username
            - name: HMRC_AC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: hmrc_ac_password
          resources:
            limits:
              memory: "100Mi"
              cpu: 100m
            requests:
              memory: "50Mi"
              cpu: 100m
