---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-postgres
  labels:
    version: 42
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-postgres
  template:
    metadata:
      labels:
        name: pttg-postgres
        version: 42
    spec:
      imagePullSecrets:
        - name: registrykey
