---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eue-api-db-provision
  labels:
    application: eue-api
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eue-api-db-provision
  template:
    metadata:
      labels:
        name: eue-api-db-provision
        deployment: eue-api-db-provision
        service: eue-api-db-provision
        schedule: businesshours
        costcentre: EUE-API
        version: {{.VERSION}}
      annotations:
        pod.beta.kubernetes.io/init-containers: '
[
    {
        "name": "pttg-postgres-bootstrap",
        "image": "quay.io/ukhomeofficedigital/pttg-postgres:latest",
        "imagePullPolicy": "Always",
        "env": [
            {
              "name": "MODE",
              "value": "bootstrap"
            },
            {
              "name": "PTTG_DB_HOSTNAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "pttg-rds-access",
                  "key": "endpoint"
                }
              }
            },
            {
              "name": "PTTG_DB_PORT",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "pttg-rds-access",
                  "key": "port"
                }
              }
            },
            {
              "name": "PTTG_DB_NAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "pttg-rds-access",
                  "key": "database"
                }
              }
            },
            {
              "name": "IP_SCHEMA_NAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "schema_name"
                }
              }
            },
            {
              "name": "IP_DB_USERNAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "application_username"
                }
              }
            },
            {
              "name": "IP_DB_PASSWORD",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "application_password"
                }
              }
            },
            {
              "name": "ROOT_DB_PASSWORD",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "pttg-rds-access",
                  "key": "password"
                }
              }
            },
            {
              "name": "IP_DB_QUERY_USERNAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "query_username"
                }
              }
            },
            {
              "name": "IP_DB_QUERY_PASSWORD",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "query_password"
                }
              }
            },
            {
              "name": "HMRC_AC_DB_NAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "hmrc_ac_database"
                }
              }
            },
            {
              "name": "HMRC_AC_DB_SCHEMA_NAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "hmrc_ac_schema_name"
                }
              }
            },
            {
              "name": "HMRC_AC_DB_USERNAME",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "hmrc_ac_username"
                }
              }
            },
            {
              "name": "HMRC_AC_DB_PASSWORD",
              "valueFrom": {
                "secretKeyRef": {
                  "name": "db-secrets",
                  "key": "hmrc_ac_password"
                }
              }
            }
          ]
    }
]'
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: pttg-postgres-query
        image: quay.io/ukhomeofficedigital/pttg-postgres:{{.VERSION}}
        imagePullPolicy: Always
        env:
          - name: MODE
            value: "query"
          - name: PTTG_DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: endpoint
          - name: PTTG_DB_PORT
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: port
          - name: PTTG_DB_NAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: database
          - name: IP_SCHEMA_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: schema_name
          - name: IP_DB_QUERY_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: query_username
          - name: IP_DB_QUERY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: query_password
          - name: HMRC_AC_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: hmrc_ac_database
          - name: HMRC_AC_DB_SCHEMA_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: hmrc_ac_schema_name
          - name: HMRC_AC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: hmrc_ac_username
          - name: HMRC_AC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: hmrc_ac_password
        resources:
         limits:
          memory: "100Mi"
          cpu: 200m
         requests:
          memory: "50Mi"
          cpu: 200m
