---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-postgres
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-postgres
  selector:
    matchLabels:
      name: pttg-postgres
  template:
    metadata:
      labels:
        name: pttg-postgres
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
      - name: registrykey
      initContainers:
      - name: pttg-postgres-bootstrap
        image: quay.io/ukhomeofficedigital/pttg-postgres:latest
        imagePullPolicy: Always
        env:
          - name: MODE
            value: "bootstrap"
          - name: PTTG_DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: endpoint
          - name: PTTG_DB_PORT
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: port
          - name: PTTG_DB_NAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: database_name
          - name: IP_SCHEMA_NAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: schema
          - name: IP_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: username
          - name: IP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: password
          - name: ROOT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: root_password
          - name: IP_DB_QUERY_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: query_username
          - name: IP_DB_QUERY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: query_password
      containers:
      - name: pttg-postgres-query
        image: quay.io/ukhomeofficedigital/pttg-postgres:latest
        imagePullPolicy: Always
        env:
          - name: MODE
            value: "query"
          - name: PTTG_DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: endpoint
          - name: PTTG_DB_PORT
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: port
          - name: PTTG_DB_NAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: database_name
          - name: IP_SCHEMA_NAME
            valueFrom:
              secretKeyRef:
                name: pttg-rds-access
                key: schema
          - name: IP_DB_QUERY_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: query_username
          - name: IP_DB_QUERY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: query_password
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
