---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-postgres
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-postgres
  template:
    spec:
