---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-postgres
  name: pttg-postgres
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: https
  selector:
    name: pttg-postgres
