---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: eue-api-db-provision
  name: eue-api-db-provision
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: https
  selector:
    name: eue-api-db-provision
