apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pttg-postgres-stop-rds-cronjob
  labels:
    version: {{.VERSION}}
    application: pttg-ip-api
spec:
  schedule: "0 20 * * *"
  successfulJobsHistoryLimit: 12
  failedJobsHistoryLimit: 12
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: pttg-postgres-stop-rds-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: pttg-postgres-stop-rds
              image: quay.io/ukhomeofficedigital/docker-pttg-rds-tools:EE-12559-remove-entrypoint-tag
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
          command: ["/bin/bash", "-ce", "source ./scripts/common.sh && ./scripts/stop-rds.sh"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: management_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: management_secret_key
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
            - name: RDS_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: db_name
            - name: STOP_RDS
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: stop_rds
